# Text Clustering using NLP

In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_excel(r"C:\Users\Priti\Downloads\Assignment-2\Data\DocumentsData.xlsx")
data.head()

Id                                           Doc Name
0   1                                     Nozzle, 220542
1   2  Value Collection 15 Inch Long x 12 Inch Wide x...
2   3  Made in USA 18 Inch Long x 13 Inch Wide x 4 mi...
3   4               8"W x 10"L 4mil Clear Reclosable Bag
4   5  Value Collection 12 Inch Long x 9 Inch Wide x ...

In [3]:
data.set_index("Id",inplace=True)

In [4]:
data.head()

Doc Name
Id                                                   
1                                      Nozzle, 220542
2   Value Collection 15 Inch Long x 12 Inch Wide x...
3   Made in USA 18 Inch Long x 13 Inch Wide x 4 mi...
4                8"W x 10"L 4mil Clear Reclosable Bag
5   Value Collection 12 Inch Long x 9 Inch Wide x ...

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 500 entries, 1 to 500
Data columns (total 1 columns):
Doc Name    500 non-null object
dtypes: object(1)
memory usage: 5.9+ KB


In [6]:
variable=data['Doc Name']

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import accuracy_score

In [8]:
cv=CountVectorizer(ngram_range=(2,2))
x1=cv.fit_transform(variable)
print(len(cv.get_feature_names()))
x2=x1.toarray()

1978


In [9]:
print(x2)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [10]:
x=x2[0:401,:]
y=x2[401:,:]

In [11]:
from sklearn.cluster import KMeans
kmeans=KMeans(n_clusters=2,random_state=0)
kmeans.fit(x)
pred=kmeans.predict(y)
print(pred)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [12]:
print(kmeans.labels_)
print(kmeans.cluster_centers_)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[[ 0.00000000e+00  0.00000000e+00  2.89389068e-02 ...  6.43086817e-03
   3.21543408e-03  9.64630225e-03]
 [ 0.00000000e+00  0.00000000e+00 -3.12250226e-17 ... -7.80625564e-18
  -3.903127